---
- name: Common (package repo + GPG key, firewalld, SELinux)
  hosts: management
  become: true
  roles:
    - common

- name: Management
  hosts: management
  become: true
  roles:
    - openzro_management
